### ISSUE TITLE
Version type deserialization broken in .NET Core 3.1

### ISSUE THREAD

**Issue by Ijwu** [ArchipelagoMW/Archipelago.MultiClient.Net#39]
.NET Core 3.1 introduced a default type converter for the Version type. Serialization still works due to the NamedTupleInterchangeConverter mimicking the previous conversion semantics for serialization. However, there is no deserializer in .NET Core 3.1 which can deserialize a Version object which was serialized with the library. (So the lib can't talk to itself, how funny is that?)

Suggestion: we implement a custom Version class, finally, which meets the spec for AP and use that. Version object seems to have served its purpose and I'm only suggesting we replace it as a result of this issue.

**Comment by Jarno458** [comment]
Is fixed in latest master, will be in the 4.1 release
