### ISSUE TITLE
Synchronous data retrievals from the DataStorage inside the websocket thread causes softlock

### ISSUE THREAD

**Issue by Jarno458** [ArchipelagoMW/Archipelago.MultiClient.Net#43]
Using the data storage for Synchronous retrieval in code that runs on websocket thread will cause the thread to wait for a Retrieved packet, but that can never be processes as the thread itself is waiting

you can reproduce this with int x = session.DataStorage["A"] inside a session.Socket.PackedReceived() handler or other code that runs on the websocket thrread like session.Locations.CheckedLocationsUpdated() handler

A workaround is to use asynchronous retreivals in such case like session.DataStorage["A"].GetAsync<int>(x => { })

I propose to add a max timeout to the synchronous retrieval and log and throw an error if this time is exceeded

**Comment by Ijwu** [comment]
Solved in #48
