### ISSUE TITLE
Expose GetDataPackage

### ISSUE THREAD

**Issue by nex3** [ArchipelagoMW/Archipelago.MultiClient.Net#81]
As far as I can tell, the `GetDataPackage` API and the data it returns isn't exposed publicly anywhere in the high-level API, and as a consequence there's no way to get an item or location's name unless it's exactly the item you most recently received. It would be useful to have access to this information one way or another.

**Comment by KonoTyran** [comment]
https://github.com/ArchipelagoMW/Archipelago.MultiClient.Net/blob/4ae40cc867818f9515e7a083d114a7d9fb22d344/Archipelago.MultiClient.Net/Helpers/LocationCheckHelper.cs#L355C1-L355C1
Can fetch location names
https://github.com/ArchipelagoMW/Archipelago.MultiClient.Net/blob/4ae40cc867818f9515e7a083d114a7d9fb22d344/Archipelago.MultiClient.Net/Helpers/ReceivedItemsHelper.cs#L123
can likewise get item names from id

**Comment by nex3** [comment]
Are those exposed as part of the public API? I couldn't figure out how to access them.

**Comment by Jarno458** [comment]
Yep they are exposed
session.Items.GetItemName()
session.Locations.GetLocationNameFromId()
The item/location groups arent exposed tho
