### ISSUE TITLE
Location name encoding can get corrupted

### ISSUE THREAD

**Issue by nex3** [ArchipelagoMW/Archipelago.MultiClient.Net#83]
When calling `session.Locations.GetLocationNameFromId()` for a location whose name is `"CD: Siegbräu"`, I received instead `"CD: Siegbr��u"`. I think maybe some part of the network/JSON infrastructure is losing the encoding information?

**Comment by Jarno458** [comment]
Intresting i never tested wierd charecters, i would need to look what is actually send by the server to see where its going wrong
